Repository biolink/biolink-model, pull requests merged in 2021-06, with the labels that each got.

#753 add faldo mappings fixes #427
  biolink-model.yaml
Labels: ready-for-release, release-2.0.0

#751 remove non-chemical (these are coming in another PR) deprecated items
  biolink-model.yaml
Labels: ready-for-release, release-2.0.0

#746 Adding new edge properties for source retrieval provenance
  biolink-model.yaml
Labels: ready-for-release, release-2.0.0

#748 reaction proposal #478
  biolink-model.yaml
  biolink/model.py
  json-schema/biolink-model.json
Labels: ready-for-release, release-2.0.0

#741 adding named thing to information content entity association and 'mentions' predicate #740
  biolink-model.yaml
Labels: ready-for-release, release-2.0.0

#733 Add Xenbase as a Gene prefix
  biolink-model.yaml
Labels: ready-for-release, release-2.0.0

#737 adding taxon relations
  biolink-model.yaml
Labels: ready-for-release, release-2.0.0

#729 fixes 727 - kept two versions of WB prefix as WormBase supports one a…
  biolink-model.yaml
Labels: ready-for-release, release-2.0.0

#692 add GO predicates for use with biological process, cellular component…
  biolink-model.yaml
Labels: ready-for-release, release-2.0.0

#699 adding missing inverses, restructuring inverses to tag the inverse only on the non-canonical predicate
  biolink-model.yaml
  biolink/model.py
  guidelines/curating-the-model.md
Labels: ready-for-release, release-2.0.0

#750 Changes suggested by the chemical working group
  Migration_2.0_Guide.md
  biolink-model.yaml
  images/chemical_entity.png
  images/reactions-cont.png
  images/reactions.png
Labels: ready-for-release, release-2.0.0

#763 first pass at property chains
  rules/property-chains.yaml
Labels: ready-for-release, release-2.0.2

#764 Adding correct parent predicates
  biolink-model.yaml
Labels: ready-for-release, release-2.0.2, working-group/predicates

#768 update documentation to include 'labeled' property graph. fixes #368
  about/mapping-neo4j.md
  about/mapping-rdf.md
Labels: ready-for-release, release-2.0.2

#774 per feedback on 2.0.0 release
  biolink-model.yaml
Labels: ready-for-release, release-2.0.2
