Repository biolink/biolink-model, pull requests merged in 2021-07, with the labels that each got.

#800 copying in jsonschema2pojo cmds from actions
  README.md
Labels: release-2.1.0

#803 add fda approval status
  biolink-model.yaml
Labels: release-2.1.0, working-group/chemical

#797 remove is_a parents from exposure classes fixes #786
  biolink-model.yaml
Labels: bug, release-2.1.0

#796 add prefixes back to protein
  biolink-model.yaml
Labels: bug, release-2.1.0

#791 behavior category mixin?
  biolink-model.yaml
Labels: bug, release-2.1.0

#784 add first option of mixin for gene chemical and gene product
  biolink-model.yaml
Labels: release-2.1.0

#772 added increases mixin and tag increases predicates with mixin (grouping for search) fixes #752
  biolink-model.yaml
Labels: release-2.1.0, working-group/predicates

#802 "contraindicated for" mapping
  biolink-model.yaml
Labels: release-2.2.0

#798 add original_ prefixes for subject, object, predicate objects fixes #761
  biolink-model.yaml
Labels: release-2.2.0

#789 Add prefixes to chemical entity branch fixes #781
  biolink-model.yaml
Labels: release-2.2.0

#813 put relation back until statisitical predicates and predicate qualifi…
  biolink-model.yaml
Labels: release-2.2.0
