Repository biolink/biolink-model, pull requests merged in 2021-08, with the labels that each got.

#799 add predicate qualifier fixes #335 fixes #625
  biolink-model.yaml
Labels: release-2.2.1

#822 bug fixes #676, fixes #663, fixes #779, fixes #107, fixes #738, fixes #824
  biolink-model.yaml
Labels: release-2.2.1

#833 UMLS STY fixes. #749 #832
  biolink-model.yaml
Labels: release-2.2.2

#838 add back in missing mixins
  biolink-model.yaml
Labels: release-2.2.2

#840 affected by hierarchy fixes fixes #836
  biolink-model.yaml
Labels: release-2.2.3

#841 adding inverses and bug fixes
  biolink-model.yaml
  biolink/model.py
Labels: release-2.2.3
